# General settings for the experiment
[debug]
debug = 0                   # Level of debug mode (0=no debug)
profile = false             # If true it will produce a profiling log with line_profiler

[settings]
device = "cpu"
model = "BERT4Rec"          # Name of the model being used
dataset = "STEAM"         # Dataset identifier 
determinism = true          # Ensure deterministic runs 
seed = 42                 # Random seed for determinism
train_batch_size = 1        # Batch size for training
test_batch_size = 1         # Batch size for testing
topk = [1, 5, 10, 20]       # K to use when sampling topk

[automata]
include_sink = "True"         # Include sink state in the target states when doing trace alignment

[generation]
targeted = true
categorized = true
similarity_threshold = 0.5  # threshold of similarity (between set of categories) above which two outputs are considered equal
ignore_genetic_split = true #whether to consider the sequence split also in the dataset generation or not
genetic_topk = 1            # the topk to use when computing scores in the dataset generation

# Settings for the evolutionary algorithm
[evolution]
generations = 10            # Number of generations in the evolutionary process
target_cat = false          # Target category (if false, it will run over all the categories)
pop_size = 8192             # Population size for the algorithm
halloffame_ratio = 0        # Ratio of the population to keep in the Hall of Fame
fitness_alpha = 0.5         # Weight to give to the sequence distance w.r.t. to the label distance
allowed_mutations = [
    "replace",              # Replace an element in a sequence
    "swap",                 # Swap two elements in a sequence
    "add",                  # Add a new element to a sequence
    "delete",               # Remove an element from a sequence
    "shuffle",              # Shuffle a subsequence
    "reverse"               # Reverse a subsequence
]                           # List of mutation types allowed in the evolution
mut_prob = 0.5              
crossover_prob = 0.7

[evolution.mutations]
num_additions = 1           # Number of additions allowed per mutation
num_deletions = 1           # Number of deletions allowed per mutatio
num_replaces = 1            # Number of replacements allowed per mutation
