[settings]
debug = 1
model = "BERT4Rec"
dataset = "ML_1M"
determinism = true

[evolution]
generations = 20
pop_size = 2048
halloffame_ratio = 0.2
allowed_mutations = ["replace", "swap", "add", "delete"] #replace, swap, add, delete, shuffle, reverse
