# General settings for the experiment
[settings]
debug = 1                   # Level of debug mode (0=no debug)
model = "BERT4Rec"          # Name of the model being used
dataset = "ML_1M"           # Dataset identifier (e.g., MovieLens 1M)
determinism = true          # Ensure deterministic runs (true = fixed seed)
train_batch_size = 1        # Batch size for training
test_batch_size = 1         # Batch size for testing

# Settings for the evolutionary algorithm
[evolution]
generations = 10            # Number of generations in the evolutionary process
pop_size = 2048             # Population size for the algorithm
halloffame_ratio = 0.2      # Ratio of the population to keep in the Hall of Fame
allowed_mutations = [
    "replace",              # Replace an element in a sequence
    "swap",                 # Swap two elements in a sequence
    "add",                  # Add a new element to a sequence
    "delete",               # Remove an element from a sequence
    "shuffle",              # Shuffle a subsequence
    "reverse"               # Reverse a subsequence
]                           # List of mutation types allowed in the evolution

# Parameters for specific mutation operations
[evolution.mutations]
num_additions = 6           # Number of additions allowed per mutation
num_deletions = 6           # Number of deletions allowed per mutation
num_replaces = 6            # Number of replacements allowed per mutation
