[settings]
debug = 1
model = "BERT4Rec"
dataset = "ML_1M"
determinism = true

[evolution]
generations = 10
pop_size = 500
halloffame_ratio = 0.2
allowed_mutations = ["replace", "swap"] #replace, swap, add, delete, shuffle, reverse
