[settings]
debug = 1
model = "BERT4Rec"
dataset = "ML_1M"
determinism = true
train_batch_size = 1
test_batch_size = 1

[evolution]
generations = 10
pop_size = 1024
halloffame_ratio = 0.2
allowed_mutations = ["replace", "swap", "add", "delete", "shuffle", "reverse"] #replace, swap, add, delete, shuffle, reverse
