# General settings for the experiment
[debug]
debug = 1                   # Level of debug mode (0=no debug)
profile = false             # If true it will produce a profiling log with line_profiler

[settings]
model = "BERT4Rec"          # Name of the model being used
dataset = "ML_1M"           # Dataset identifier 
determinism = true         # Ensure deterministic runs 
train_batch_size = 1        # Batch size for training
test_batch_size = 1         # Batch size for testing
topk = 5                  # K to use when sampling topk

[automata]
include_sink = false # Include sink state in the target states when doing trace alignment

[generation]
strategy = "genetic_categorized"    # [exhaustive, genetic, genetic_categorized]
similarity_threshold = 0.7             # threshold of jaccard similarity (between set of categories) above which two outputs are considered equal

# Settings for the evolutionary algorithm
[evolution]
generations = 20            # Number of generations in the evolutionary process
pop_size = 2048             # Population size for the algorithm
halloffame_ratio = 0.2      # Ratio of the population to keep in the Hall of Fame
fitness_alpha = 0.5         # Weight to give to the sequence distance w.r.t. to the label distance
allowed_mutations = [
    "replace",              # Replace an element in a sequence
    "swap",                 # Swap two elements in a sequence
    "add",                  # Add a new element to a sequence
    "delete",               # Remove an element from a sequence
    "shuffle",              # Shuffle a subsequence
    "reverse"               # Reverse a subsequence
]                           # List of mutation types allowed in the evolution
mut_prob = 0.2              
crossover_prob = 0.9

# Parameters for specific mutation operations
[evolution.mutations]
num_additions = 4           # Number of additions allowed per mutation
num_deletions = 4           # Number of deletions allowed per mutation
num_replaces = 4            # Number of replacements allowed per mutation
